### ISSUE TITLE
Is println special-cased in loops?

### ISSUE THREAD

**Issue by SolalPirelli** [epfldata/sc-public#13]
My code contains a loop like `dsl"""for( ... ) println( ... )"""`. This works fine. However, replacing `println` by anything else, such as `print` or even `System.out.println` causes a compilation failure, complaining that `Unit` was found but `QQGenerated.this.Rep[Unit]` was expected.

Did you special-case the `println` function to work in loops? How can we get another function to work? (I'm particularly interested in `print`, i.e. without a newline)

**Comment by LPTK** [comment]
This is actually because `print` is not part of the deeply-embedded functions. See [this](https://github.com/epfldata/sc-public/blob/master/doc/DebuggingQuasiquotes.md#missing-deep-representation) for more details.
The reason you don't get the error in other cases is that when the result of `print` is not used, it will simply fall back to the `print` of the current program (the program generator) instead of generating a `print` instruction.

**Comment by LPTK** [comment]
I added a section for that issue in the [FAQ](https://github.com/epfldata/sc-public/blob/master/doc/FAQ.md#why-does-the-print-function-not-work).
